server:
  port: 8888

spring:
  application:
    name: vault-config-server

  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/IdeaProjects/spring-cloud-config-vault/vault-config-server