#spring:
#  application:
#    name: vault-config-server
#
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/nastib/vault-config-server.git # file://${user.home}/IdeaProjects/spring-cloud-config-vault/vault-config-server